name: Test

on:
  push:
    branches: [main, develop, ci]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-xcframework:
    runs-on: macos-26
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build XCFramework
        run: ./scripts/xcframework.sh

      - name: Verify XCFramework with Swift Package
        run: swift build --package-path swift-package
